parameters:
    octava_branching.service.dump_table.logger.class: Symfony\Bridge\Monolog\Logger
    octava_branching.service.dump_table.logger.file_handler.class: Monolog\Handler\StreamHandler
    octava_branching.service.dump_table.logger.memory_processor.class: Monolog\Processor\MemoryPeakUsageProcessor

services:
    _defaults:
        public: false
        autoconfigure: true
        autowire: true

    Octava\Bundle\BranchingBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']

    Octava\Bundle\BranchingBundle\Config\:
        resource: '../../Config'

    Octava\Bundle\BranchingBundle\Helper\Database:
        public: true
        arguments:
            - '%kernel.root_dir%'
            - '%octava_branching.copy_db_data%'
            - '%database_driver%'
            - '%database_host%'
            - '%database_port%'
            - '%database_user%'
            - '%database_password%'
            - '%database_name%'
            - '%database_name_original%'

    Octava\Bundle\BranchingBundle\Twig\BranchingExtension:
        public: false
        arguments: ['%kernel.root_dir%', '%kernel.environment%']
        tags:
            - { name: twig.extension }

    octava_branching.service.dump_table.logger.file_handler:
        class: '%octava_branching.service.dump_table.logger.file_handler.class%'
        arguments: ['%kernel.logs_dir%/OctavaBranchingBundle/dump_table/dump_table.log', 200]

    octava_branching.service.dump_table.logger.memory_processor:
        class: '%octava_branching.service.dump_table.logger.memory_processor.class%'

    octava_branching.service.dump_table.logger:
        class: '%octava_branching.service.dump_table.logger.class%'
        arguments:
            - 'r12n_project.sync'
            - ['@octava_branching.service.dump_table.logger.file_handler']
            - ['@octava_branching.service.dump_table.logger.memory_processor']

    Octava\Bundle\BranchingBundle\Service\DumpTable:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@octava_branching.service.dump_table.logger'
