services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Octava\Bundle\BranchingBundle\Config\:
        resource: '../../Config/*'

    Octava\Bundle\BranchingBundle\Manager\:
        resource: '../../Manager/*'
        public: true

    Octava\Bundle\BranchingBundle\Twig\BranchingExtension:
        arguments: ['%kernel.project_dir%', '%kernel.environment%']
        tags:
            - { name: twig.extension }
