parameters:
    branching.helper.database.class: Octava\Bundle\BranchingBundle\Helper\Database
    branching.twig.branching_extension.class: Octava\Bundle\BranchingBundle\Twig\BranchingExtension

services:
    branching.helper.database:
        class: %branching.helper.database.class%
        arguments:
            - %kernel.root_dir%
            - %branching.copy_db_data%
            - %database_driver%
            - %database_host%
            - %database_port%
            - %database_user%
            - %database_password%
            - %database_name%
            - %database_name_original%

    branching.twig.branching_extension:
        class: %branching.twig.branching_extension.class%
        public: false
        arguments: [%kernel.root_dir%, %kernel.environment%]
        tags:
            - { name: twig.extension }
